In [63]:
from pycocotools.cocoeval import COCOeval
import json
import torch
import transform as transf
from torchvision.transforms import Compose
import yaml
from dataset import MedicalBboxDataset
from model import ResNet50
import numpy as np
from utils import bbox_collate, data2target, calc_confusion_matrix, draw_graph

In [71]:
def evaluate_coco(val, threshold=0.05):
    config = yaml.safe_load(open('./config.yaml'))
    dataset_means = json.load(open(config['dataset']['mean_file']))
    dataset_all = MedicalBboxDataset(
        config['dataset']['annotation_file'],
        config['dataset']['image_root'])
    if 'class_integration' in config['dataset']:
        dataset_all = dataset_all.integrate_classes(
            config['dataset']['class_integration']['new'],
            config['dataset']['class_integration']['map'])
    
    transform = Compose([
        transf.ToFixedSize([config['inputsize']] * 2),  # inputsize x inputsizeの画像に変換
        transf.Normalize(dataset_means['mean'], dataset_means['std']),
        transf.HWCToCHW()
        ])

    dataset = dataset_all.split(val, config['dataset']['split_file'])
    dataset.set_transform(transform)
    
    model = torch.load(f'/data/unagi0/masaoka/retinanet/retinanet50_[{val}].pt')
    model = model.cuda()
    model.eval()
    with torch.no_grad():

        # start collecting results
        results = []
        image_ids = []

        for index in range(len(dataset)):
            data = dataset[index]
            scale = 1   #data['scale']
            data['img'] = torch.from_numpy(data['img']) #.permute(2, 0, 1)
            

            # run network
            if torch.cuda.is_available():
                scores, labels, boxes = model(data['img'].cuda().float().unsqueeze(dim=0))
               
            else:
                scores, labels, boxes = model(data['img'].float().unsqueeze(dim=0))
            scores = scores.cpu()
            labels = labels.cpu()
            boxes  = boxes.cpu()

            # correct boxes for image scale
            boxes /= scale

            if boxes.shape[0] > 0:
                # change to (x, y, w, h) (MS COCO standard)
                boxes[:, 2] -= boxes[:, 0]
                boxes[:, 3] -= boxes[:, 1]

                # compute predicted labels and scores
                #for box, score, label in zip(boxes[0], scores[0], labels[0]):
                for box_id in range(boxes.shape[0]):
                    score = float(scores[box_id])
                    label = int(labels[box_id])
                    box = boxes[box_id, :]

                    # scores are sorted, so we can break
                    if score < threshold:
                        break

                    # append detection for each positively labeled class
                    image_result = {
                        'image_id'    : dataset.imgids[index],
                        'category_id' : dataset.label_to_coco_label(label),
                        'score'       : float(score),
                        'bbox'        : box.tolist(),
                    }

                    # append detection to results
                    results.append(image_result)

            # append image to list of processed images
            image_ids.append(dataset.imgids[index])

            # print progress
            print('{}/{}'.format(index+1, len(dataset)), end='\r')

        if not len(results):
            print("error")
            return
        # write output
        json.dump(results, open(f'/data/unagi0/masaoka/retinanet/bbox_results{val}.json', 'w'), indent=4)

        # load results in COCO evaluation tool
        coco_true = dataset.coco
        coco_pred = coco_true.loadRes(f'/data/unagi0/masaoka/retinanet/bbox_results{val}.json')

        # run COCO evaluation
        coco_eval = COCOeval(coco_true, coco_pred, 'bbox')
        coco_eval.params.imgIds = image_ids
        coco_eval.evaluate()
        coco_eval.accumulate()
        coco_eval.summarize()

        return
    

In [72]:
evaluate_coco(0)
evaluate_coco(1)

loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
creating index...
index created!
creating index...
index created!


/home/mil/masaoka/.pyenv/versions/anaconda3-2019.10/envs/cuda9/lib/python3.8/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'retinanet.losses.FocalLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)


Loading and preparing results...
DONE (t=3.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=11.47s).
Accumulating evaluation results...
DONE (t=7.72s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.016
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.014
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.017
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.096
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.136
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=

In [2]:
def evaluate_coco_weak(val, threshold=0.05):
    config = yaml.safe_load(open('./config.yaml'))
    dataset_means = json.load(open(config['dataset']['mean_file']))
    dataset_all = MedicalBboxDataset(
        config['dataset']['annotation_file'],
        config['dataset']['image_root'])
    if 'class_integration' in config['dataset']:
        dataset_all = dataset_all.integrate_classes(
            config['dataset']['class_integration']['new'],
            config['dataset']['class_integration']['map'])
    
    transform = Compose([
        transf.ToFixedSize([config['inputsize']] * 2),  # inputsize x inputsizeの画像に変換
        transf.Normalize(dataset_means['mean'], dataset_means['std']),
        transf.HWCToCHW()
        ])

    dataset = dataset_all.split(val, config['dataset']['split_file'])
    dataset.set_transform(transform)
    
    model = ResNet50()
    model.load_state_dict(torch.load(f"/data/unagi0/masaoka/resnet50_classify_rotate_flip_shear[{val}].pt"))
    

    results = []
    image_ids = []
    for index in range(len(dataset)):
        data = dataset[index]
        scale = 1   #data['scale']
        data['img'] = torch.from_numpy(data['img']) #.permute(2, 0, 1)
        # run network
        if torch.cuda.is_available():
            #scores, labels, boxes = model(data['img'].cuda().float().unsqueeze(dim=0))
            scores, labels, boxes = model(data['img'].unsqueeze(0).float(), e=True, aug=False)
        else:
            scores, labels, boxes = model(data['img'].float().unsqueeze(dim=0), e=True, aug=True)
        scores = scores.cpu()
        labels = labels.cpu()
        boxes  = boxes.cpu()

        # correct boxes for image scale
        boxes /= scale

        if boxes.shape[0] > 0:
            # change to (x, y, w, h) (MS COCO standard)
            boxes[:, 2] -= boxes[:, 0]
            boxes[:, 3] -= boxes[:, 1]

            # compute predicted labels and scores
            #for box, score, label in zip(boxes[0], scores[0], labels[0]):
            for box_id in range(boxes.shape[0]):
                score = float(scores[box_id])
                label = int(labels[box_id])
                box = boxes[box_id, :]
                

                # scores are sorted, so we can break
                if score < threshold:
                    break

                # append detection for each positively labeled class
                image_result = {
                        'image_id'    : dataset.imgids[index],
                        'category_id' : dataset.label_to_coco_label(label),
                        'score'       : float(score),
                        'bbox'        : box.tolist(),
                    }

                # append detection to results
                results.append(image_result)

        # append image to list of processed images
        image_ids.append(dataset.imgids[index])

        # print progress
        print('{}/{}'.format(index+1, len(dataset)), end='\r')

    if not len(results):
            print("error")
            return
        # write output
    json.dump(results, open(f'/data/unagi0/masaoka/retinanet/bbox_results_resnet50c{val}.json', 'w'), indent=4)

    # load results in COCO evaluation tool
    coco_true = dataset.coco
    coco_pred = coco_true.loadRes(f'/data/unagi0/masaoka/retinanet/bbox_results_resnet50c{val}.json')

    # run COCO evaluation
    coco_eval = COCOeval(coco_true, coco_pred, 'bbox')
    coco_eval.params.imgIds = image_ids
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()
    return

In [3]:
evaluate_coco_weak(0)

loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
creating index...
index created!
creating index...
index created!


/opt/conda/conda-bld/pytorch_1587428132279/work/aten/src/ATen/native/BinaryOps.cpp:66: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.


Loading and preparing results...
DONE (t=0.29s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=2.75s).
Accumulating evaluation results...
DONE (t=0.92s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.006
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.053
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.110
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1

In [72]:
def evaluate_classify(val, threshold=0.05):
    config = yaml.safe_load(open('./config.yaml'))
    dataset_means = json.load(open(config['dataset']['mean_file']))
    dataset_all = MedicalBboxDataset(
        config['dataset']['annotation_file'],
        config['dataset']['image_root'])
    if 'class_integration' in config['dataset']:
        dataset_all = dataset_all.integrate_classes(
            config['dataset']['class_integration']['new'],
            config['dataset']['class_integration']['map'])
    
    transform = Compose([
        transf.ToFixedSize([config['inputsize']] * 2),  # inputsize x inputsizeの画像に変換
        transf.Normalize(dataset_means['mean'], dataset_means['std']),
        transf.HWCToCHW()
        ])

    dataset = dataset_all.split(val, config['dataset']['split_file'])
    dataset.set_transform(transform)
    dataloader_val = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=False, 
                                                num_workers=4, collate_fn=bbox_collate)
    model = ResNet50()
    model.load_state_dict(torch.load(f"/data/unagi0/masaoka/resnet50_classify0.pt"))
    ite = 0
    gt = [0,0,0,0]
    tpa = np.zeros(3)
    fpa = np.zeros(3)
    tna = 0
    fna = np.zeros(3)
    with torch.no_grad():
        for i, d in enumerate(dataloader_val):
            scores = torch.sigmoid(model(d['img'].cuda().float()))
            print(scores)
            """target = np.zeros(3)
            for x in d["annot"]:
                target[int(x[0][4])] = 1"""
            output = scores.cpu().data.numpy()
            output = np.where(output>0.5,1,0)
            target, n, t, v, u = data2target(d, torch.from_numpy(output))
            target = target.cpu().data.numpy()
            gt = np.array([n,t,v,u])
            tp, fp, fn, tn = calc_confusion_matrix(output, target, gt)
            tpa += tp
            fpa += fp
            fna += fn
            tna += tn
                
            print(f'{i}/{len(dataset)}', end = '\r')
    print(gt,tpa,fpa,tna,fna)
    return gt,tpa,fpa,tna,fna
        
        
        

In [73]:
evaluate_classify(4)

loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
creating index...
index created!
creating index...
index created!
tensor([[9.9898e-01, 1.8225e-04, 5.5393e-08]], device='cuda:0')
tensor([[1.0000e+00, 6.3562e-07, 3.1253e-10]], device='cuda:0')
tensor([[1.0000e+00, 5.4637e-06, 4.1242e-10]], device='cuda:0')
tensor([[9.9996e-01, 2.5933e-06, 4.7217e-10]], device='cuda:0')
tensor([[1.0000e+00, 6.9260e-06, 2.7466e-10]], device='cuda:0')
tensor([[1.0000e+00, 6.6762e-06, 1.3004e-09]], device='cuda:0')
tensor([[1.0000e+00, 3.6007e-05, 9.8349e-11]], device='cuda:0')
tensor([[1.0000e+00, 1.9932e-05, 1.0198e-09]], device='cuda:0')
tensor([[9.9997e-01, 4.3802e-06, 1.7095e-09]], device='cuda:0')
tensor([[1.0000e+00, 1.2542e-04, 2.3301e-09]], device='cuda:0')
tensor([[1.0000e+00, 4.3376e-04, 2.1709e-06]], device='cuda:0')
tensor([[9.9947e-01, 1.8118e-04, 9.1796e-07]], device='cuda:0')
tensor([[9.9527e-01, 1.2288e-05, 2.7291e-08]], device='cuda:0')
tensor([[2.7707e-03

tensor([[1.0000e+00, 2.1682e-04, 1.5704e-09]], device='cuda:0')
tensor([[1.0000e+00, 6.1634e-07, 3.9332e-11]], device='cuda:0')
tensor([[1.0000e+00, 2.9446e-04, 2.3667e-06]], device='cuda:0')
tensor([[1.0000e+00, 1.0285e-05, 3.3055e-10]], device='cuda:0')
tensor([[1.0000e+00, 1.6648e-06, 1.6590e-11]], device='cuda:0')
tensor([[1.0000e+00, 7.3488e-06, 3.8076e-09]], device='cuda:0')
tensor([[1.0000e+00, 6.2368e-06, 1.4210e-08]], device='cuda:0')
tensor([[1.0000e+00, 6.9666e-06, 5.4892e-09]], device='cuda:0')
tensor([[1.0000e+00, 1.0142e-06, 7.5731e-10]], device='cuda:0')
tensor([[1.0000e+00, 4.7706e-06, 4.9532e-09]], device='cuda:0')
tensor([[1.0000e+00, 8.7792e-07, 3.3753e-11]], device='cuda:0')
tensor([[1.0000e+00, 1.1059e-06, 2.5618e-10]], device='cuda:0')
tensor([[1.0000e+00, 2.7160e-06, 4.3978e-10]], device='cuda:0')
tensor([[1.0000e+00, 1.7205e-06, 4.5176e-09]], device='cuda:0')
tensor([[1.0000e+00, 6.2742e-06, 3.8795e-10]], device='cuda:0')
tensor([[1.0000e+00, 1.3611e-06, 5.2709e

tensor([[1.0000e+00, 2.7875e-07, 9.0119e-11]], device='cuda:0')
tensor([[1.0000e+00, 1.3088e-05, 1.3399e-09]], device='cuda:0')
tensor([[1.0000e+00, 4.7485e-05, 7.2501e-08]], device='cuda:0')
tensor([[1.0000e+00, 4.9097e-05, 1.5299e-07]], device='cuda:0')
tensor([[1.0000e+00, 1.2742e-05, 3.5003e-08]], device='cuda:0')
tensor([[1.0000e+00, 7.5424e-05, 1.1401e-07]], device='cuda:0')
tensor([[1.0000e+00, 9.0204e-05, 1.4199e-07]], device='cuda:0')
tensor([[1.0000e+00, 4.2962e-05, 4.8844e-08]], device='cuda:0')
tensor([[9.9998e-01, 1.4881e-04, 2.1271e-07]], device='cuda:0')
tensor([[1.0000e+00, 2.6810e-04, 1.5530e-07]], device='cuda:0')
tensor([[9.9998e-01, 9.7130e-05, 1.1229e-07]], device='cuda:0')
tensor([[1.0000e+00, 7.9448e-05, 8.7534e-09]], device='cuda:0')
tensor([[1.0000e+00, 4.4142e-05, 5.2344e-08]], device='cuda:0')
tensor([[1.0000e+00, 7.6600e-05, 3.0874e-08]], device='cuda:0')
tensor([[1.0000e+00, 6.0995e-05, 1.3741e-08]], device='cuda:0')
tensor([[1.0000e+00, 5.1120e-05, 1.2231e

KeyboardInterrupt: 

In [64]:
tpa,fpa,tna,fna  = [[],[],[]], [[],[],[]], [[],[],[]], [[],[],[]],
for i in range(5):
    gt, tp,fp,tn,fn = evaluate_classify(i)
    for i in range(3):
        tpa[i].append(tp[i])
        fpa[i].append(fp[i])
        fna[i].append(fn[i])
        tna[i].append(sum(gt)-tp[i]-fp[i]-fn[i])
print(tpa)
print(fpa)
print(tna)
print(fna)

loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
creating index...
index created!
creating index...
index created!
[982, 75, 76, 5914] [624, 62, 75] [282, 33, 0] [5590] [358, 13, 1]
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
creating index...
index created!
creating index...
index created!
[914, 141, 76, 6572] [826, 67, 76] [172, 219, 0] [6189] [88, 74, 0]
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
creating index...
index created!
creating index...
index created!
[820, 94, 76, 7379] [792, 71, 76] [380, 6, 0] [6972] [28, 23, 0]
loading annotations into memory...
Done (t=0.36s)
creating index...
index created!
creating index...
index created!
creating index...
index created!
[1101, 77, 75, 7781] [1029, 63, 75] [1359, 40, 0] [6342] [72, 14, 0]
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
creating index...
index created!
creating index...
i

In [1]:
import torch
import numpy as np

In [19]:
a = torch.tensor([0.1,0.5,0.6,0.3]).requires_grad_()
c = torch.tensor([1,1,1,1])
d = torch.tensor([0,0,0,0])
b = torch.where(a>0.5, 1., 0.)
loss = (b).sum()
loss.backward()

TypeError: where(): argument 'input' (position 2) must be Tensor, not float

In [16]:
print(a.grad)

tensor([0.2000, 1.0000, 1.2000, 0.6000])


In [4]:
torch.zeros_like(np.array([1,2]))

TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [2]:
a = np.array([[1,0,0], 
                        [0,0,0], 
                        [0,1,1]])

b = np.array([[1,0,0],
                        [0,0,0],
                        [0,1,0]])
result = np.all((a-b)==0,axis=1)
np.all((1-a)*(1-b), axis = 1).sum()

1

In [7]:
torch.sigmoid(torch.from_numpy(a).float())

tensor([[0.7311, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.7311, 0.7311]])

In [3]:
c = b*a
c

array([[1, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [59]:
c.sum(axis = 0)

array([2, 1, 1])

In [56]:
c[2] = 1

In [62]:
1/(c.sum(axis = 0) + 1)

array([0.33333333, 0.5       , 0.5       ])

In [63]:
c = c.sum(axis=0)

In [34]:
c=np.array([[1,0,9],
                        [0,0,0],
                        [0,1,10]])

In [36]:
c.sum(axis=1)

array([10,  0, 11])

In [66]:
c

array([2, 1, 1])

In [67]:
c[0]

2

In [83]:
a = torch.tensor([1,2]*5).reshape(-1,2)

In [84]:
a

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

In [87]:
a=np.array([1])
a.ndim

1